version: '3.7'
services:
   client:
      build:
         context: ./myapp
         dockerfile: Dockerfile
      tty: true
      ports:
         - "3000:3000"
      volumes:
         - ./myapp:/app
         - /app/node_modules