orbs:
  node: circleci/node@4.2.1

version: 2.1

jobs:
   build:
      docker:
        - image: circleci/golang:1.15
      steps:
        - checkout
        - setup_remote_docker:
            docker_layer_caching: true
          # build
        - run: docker build -t hesam80/dwa .
        - run: docker image ls
        - run: docker run --name dwa -d -p 49160:8080 hesam80/dwa:latest
        - run: docker run --mount source=datastore,destination=/mnt/volume debian:bullseye-slim dd if=/dev/zero of=/mnt/volume/zero bs=32M count=32
        - run: docker image ls
        - run: docker volume ls
        - run: docker ps
        - run: docker logs dwa
        - run: which curl
        - run: docker exec -it dwa /usr/bin/bash which curl
workflows:
  app-tests:
    jobs:
      - build