version: 2  
 jobs:
   one:

   steps:
      # ... steps for building/testing app ...

      - setup_remote_docker:
          version: 19.03.13
      - run: |
      
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t flaskapp:$TAG .
          echo $DOCKER_PASS | docker login -u hesam80 -p sa13801380