version: 2.1
jobs:
  build:
    docker:
      - image: python:3.7
    steps:
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
            pip install docker
            pip install --upgrade pip
            pip install build
      - run:
          name: Code Has Arrived
          command: |
            ls -al
            echo '^^^That should look familiar^^^'
    
jobs:
  build:
    docker:
      - image: circleci/golang:1.15
        auth:
          username: hesam80
          password: sa13801380  # context / project UI env-var reference
    steps:
      - checkout
      # ... steps for building/testing app ...

      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true

      # build and push Docker image
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t flaskapp:$TAG .
          echo $DOCKER_PASS | docker login -u hesam80 -p sa13801380
          
