version: 2  
job:
  one:
    docker:
      - image: circleci/golang:1.15
        auth:
          username: hesam80
          password: sa13801380  # context / project UI env-var reference
    steps:
      - checkout
      # ... steps for building/testing app ...

      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      # build and push Docker image
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          echo $TAG
          #docker build -t jsproject:$TAG .