name: CI to Docker Hub
on:
  schedule:
    - cron: '0 10 * * *' # everyday at 10am
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - workflow
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/flaskapp:${{ github.sha }}
          
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}


  todeploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout and build image from repo
        uses: actions/checkout@v2
      - name: deploy action step
        uses: hesam80/fandogh-service-deploy-action@v1.2.0
        with:
          username: hesam80
          password: sa13801380
          image_name: hesam80/flaskapp
          path_to_service_file: ./flaskapp.yml