name: Deploy
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: deploy action step
        uses: Glyphack/fandogh-service-deploy-action@v1
        with:
          username: ${{ secrets.FANDOGH_USERNAME }}
          password: ${{ secrets.FANDOGH_PASSWORD }}
          image_name: my_image
          image_version: v1
          path_to_service_file: ./flaskapp.yml

