name: 'deploy fandogh serivce'
description: 'deploy image to fandogh using `service.yml` file'
inputs:
  username: 'hesam80'
    description: 'fandogh cloud username'
    required: true
  password: 'sa13801380'
    description: 'fandogh cloud password'
    required: true
  image_name: flaskapp
    description: 'name of the image'
    required: true
  image_version: '0.1'
    description: 'version of image'
    required: true
  path_to_service_file: './flaskapp.yml'
    description: 'path to service defention file'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.username }}
    - ${{ inputs.password }}
    - ${{ inputs.image_name }}
    - ${{ inputs.image_version }}
    - ${{ inputs.path_to_service_file }}
    