name: Deploy
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - workflow
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout and build image from repo
        uses: actions/checkout@v2
      - name: deploy action step
        uses: hesam80/fandogh-service-deploy-action@v1.2.0
        with:
          username: hesam80
          password: sa13801380
          image_name: hesam80/flaskapp
          path_to_service_file: ./flaskapp.yml

